[package]
name = "hamm"
version = "0.1.0"
authors = ["rustycat17 <rustycat17@posteo.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
